In [1]:
import pandas as pd

In [2]:
!pip install seaborn

Requirement already satisfied: seaborn in c:\users\user\documents\myproject\datamining\data_mining_project2\data_mining_student_performance\env\lib\site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in c:\users\user\documents\myproject\datamining\data_mining_project2\data_mining_student_performance\env\lib\site-packages (from seaborn) (2.2.6)
Requirement already satisfied: pandas>=1.2 in c:\users\user\documents\myproject\datamining\data_mining_project2\data_mining_student_performance\env\lib\site-packages (from seaborn) (2.3.3)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in c:\users\user\documents\myproject\datamining\data_mining_project2\data_mining_student_performance\env\lib\site-packages (from seaborn) (3.10.8)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\user\documents\myproject\datamining\data_mining_project2\data_mining_student_performance\env\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.2)
Requirement already satisfied: cycler>=0.10 in c:\users\user\documents\myproject\datamining\data_mining_project2\data_mining_student_performance\env\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\user\documents\myproject\datamining\data_mining_project2\data_mining_student_performance\env\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\user\documents\myproject\datamining\data_mining_project2\data_mining_student_performance\env\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\users\user\documents\myproject\datamining\data_mining_project2\data_mining_student_performance\env\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (26.0)
Requirement already satisfied: pillow>=8 in c:\users\user\documents\myproject\datamining\data_mining_project2\data_mining_student_performance\env\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (12.1.1)
Requirement already satisfied: pyparsing>=3 in c:\users\user\documents\myproject\datamining\data_mining_project2\data_mining_student_performance\env\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\user\documents\myproject\datamining\data_mining_project2\data_mining_student_performance\env\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\user\documents\myproject\datamining\data_mining_project2\data_mining_student_performance\env\lib\site-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\user\documents\myproject\datamining\data_mining_project2\data_mining_student_performance\env\lib\site-packages (from pandas>=1.2->seaborn) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\user\documents\myproject\datamining\data_mining_project2\data_mining_student_performance\env\lib\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)

## Import Libraries

In [3]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler, LabelEncoder
from sklearn.impute import KNNImputer
from sklearn.feature_selection import SelectKBest, f_regression
from sklearn.ensemble import RandomForestRegressor

In [5]:
import os
print(os.getcwd())  
print(os.listdir())

C:\Users\User\Documents\MyProject\DataMining\Data_mining_project2\Data_mining_student_performance\notebooks
['.ipynb_checkpoints', 'data_preprocessing.ipynb', 'student-mat.csv']

In [6]:
import os
print(os.getcwd())

C:\Users\User\Documents\MyProject\DataMining\Data_mining_project2\Data_mining_student_performance\notebooks

## Load Dataset

In [7]:
df = pd.read_csv("student-mat.csv", sep=';')
print(df.head())

                                              school  sex  age  address  \
0  GP;"F";18;"U";"GT3";"A";4;4;"at_home";"teacher...  NaN  NaN      NaN
1  GP;"F";17;"U";"GT3";"T";1;1;"at_home";"other";...  NaN  NaN      NaN
2  GP;"F";15;"U";"LE3";"T";1;1;"at_home";"other";...  NaN  NaN      NaN
3  GP;"F";15;"U";"GT3";"T";4;2;"health";"services...  NaN  NaN      NaN
4  GP;"F";16;"U";"GT3";"T";3;3;"other";"other";"h...  NaN  NaN      NaN

   famsize  Pstatus  Medu  Fedu  Mjob  Fjob  ...  famrel  freetime  goout  \
0      NaN      NaN   NaN   NaN   NaN   NaN  ...     NaN       NaN    NaN
1      NaN      NaN   NaN   NaN   NaN   NaN  ...     NaN       NaN    NaN
2      NaN      NaN   NaN   NaN   NaN   NaN  ...     NaN       NaN    NaN
3      NaN      NaN   NaN   NaN   NaN   NaN  ...     NaN       NaN    NaN
4      NaN      NaN   NaN   NaN   NaN   NaN  ...     NaN       NaN    NaN

   Dalc  Walc  health  absences  G1  G2  G3
0   NaN   NaN     NaN       NaN NaN NaN NaN
1   NaN   NaN     NaN       NaN NaN NaN NaN
2   NaN   NaN     NaN       NaN NaN NaN NaN
3   NaN   NaN     NaN       NaN NaN NaN NaN
4   NaN   NaN     NaN       NaN NaN NaN NaN

[5 rows x 33 columns]

In [8]:
import pandas as pd

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

df = pd.read_csv("student-mat.csv", sep=';')
print(df)

                                                school  sex  age  address  \
0    GP;"F";18;"U";"GT3";"A";4;4;"at_home";"teacher...  NaN  NaN      NaN
1    GP;"F";17;"U";"GT3";"T";1;1;"at_home";"other";...  NaN  NaN      NaN
2    GP;"F";15;"U";"LE3";"T";1;1;"at_home";"other";...  NaN  NaN      NaN
3    GP;"F";15;"U";"GT3";"T";4;2;"health";"services...  NaN  NaN      NaN
4    GP;"F";16;"U";"GT3";"T";3;3;"other";"other";"h...  NaN  NaN      NaN
5    GP;"M";16;"U";"LE3";"T";4;3;"services";"other"...  NaN  NaN      NaN
6    GP;"M";16;"U";"LE3";"T";2;2;"other";"other";"h...  NaN  NaN      NaN
7    GP;"F";17;"U";"GT3";"A";4;4;"other";"teacher";...  NaN  NaN      NaN
8    GP;"M";15;"U";"LE3";"A";3;2;"services";"other"...  NaN  NaN      NaN
9    GP;"M";15;"U";"GT3";"T";3;4;"other";"other";"h...  NaN  NaN      NaN
10   GP;"F";15;"U";"GT3";"T";4;4;"teacher";"health"...  NaN  NaN      NaN
11   GP;"F";15;"U";"GT3";"T";2;1;"services";"other"...  NaN  NaN      NaN
12   GP;"M";15;"U";"LE3";"T";4;4;"health";"services...  NaN  NaN      NaN
13   GP;"M";15;"U";"GT3";"T";4;3;"teacher";"other";...  NaN  NaN      NaN
14   GP;"M";15;"U";"GT3";"A";2;2;"other";"other";"h...  NaN  NaN      NaN
15   GP;"F";16;"U";"GT3";"T";4;4;"health";"other";"...  NaN  NaN      NaN
16   GP;"F";16;"U";"GT3";"T";4;4;"services";"servic...  NaN  NaN      NaN
17   GP;"F";16;"U";"GT3";"T";3;3;"other";"other";"r...  NaN  NaN      NaN
18   GP;"M";17;"U";"GT3";"T";3;2;"services";"servic...  NaN  NaN      NaN
19   GP;"M";16;"U";"LE3";"T";4;3;"health";"other";"...  NaN  NaN      NaN
20   GP;"M";15;"U";"GT3";"T";4;3;"teacher";"other";...  NaN  NaN      NaN
21   GP;"M";15;"U";"GT3";"T";4;4;"health";"health";...  NaN  NaN      NaN
22   GP;"M";16;"U";"LE3";"T";4;2;"teacher";"other";...  NaN  NaN      NaN
23   GP;"M";16;"U";"LE3";"T";2;2;"other";"other";"r...  NaN  NaN      NaN
24   GP;"F";15;"R";"GT3";"T";2;4;"services";"health...  NaN  NaN      NaN
25   GP;"F";16;"U";"GT3";"T";2;2;"services";"servic...  NaN  NaN      NaN
26   GP;"M";15;"U";"GT3";"T";2;2;"other";"other";"h...  NaN  NaN      NaN
27   GP;"M";15;"U";"GT3";"T";4;2;"health";"services...  NaN  NaN      NaN
28   GP;"M";16;"U";"LE3";"A";3;4;"services";"other"...  NaN  NaN      NaN
29   GP;"M";16;"U";"GT3";"T";4;4;"teacher";"teacher...  NaN  NaN      NaN
30   GP;"M";15;"U";"GT3";"T";4;4;"health";"services...  NaN  NaN      NaN
31   GP;"M";15;"U";"GT3";"T";4;4;"services";"servic...  NaN  NaN      NaN
32   GP;"M";15;"R";"GT3";"T";4;3;"teacher";"at_home...  NaN  NaN      NaN
33   GP;"M";15;"U";"LE3";"T";3;3;"other";"other";"c...  NaN  NaN      NaN
34   GP;"M";16;"U";"GT3";"T";3;2;"other";"other";"h...  NaN  NaN      NaN
35   GP;"F";15;"U";"GT3";"T";2;3;"other";"other";"o...  NaN  NaN      NaN
36   GP;"M";15;"U";"LE3";"T";4;3;"teacher";"service...  NaN  NaN      NaN
37   GP;"M";16;"R";"GT3";"A";4;4;"other";"teacher";...  NaN  NaN      NaN
38   GP;"F";15;"R";"GT3";"T";3;4;"services";"health...  NaN  NaN      NaN
39   GP;"F";15;"R";"GT3";"T";2;2;"at_home";"other";...  NaN  NaN      NaN
40   GP;"F";16;"U";"LE3";"T";2;2;"other";"other";"h...  NaN  NaN      NaN
41   GP;"M";15;"U";"LE3";"T";4;4;"teacher";"other";...  NaN  NaN      NaN
42   GP;"M";15;"U";"GT3";"T";4;4;"services";"teache...  NaN  NaN      NaN
43   GP;"M";15;"U";"GT3";"T";2;2;"services";"servic...  NaN  NaN      NaN
44   GP;"F";16;"U";"LE3";"T";2;2;"other";"at_home";...  NaN  NaN      NaN
45   GP;"F";15;"U";"LE3";"A";4;3;"other";"other";"c...  NaN  NaN      NaN
46   GP;"F";16;"U";"LE3";"A";3;3;"other";"services"...  NaN  NaN      NaN
47   GP;"M";16;"U";"GT3";"T";4;3;"health";"services...  NaN  NaN      NaN
48   GP;"M";15;"U";"GT3";"T";4;2;"teacher";"other";...  NaN  NaN      NaN
49   GP;"F";15;"U";"GT3";"T";4;4;"services";"teache...  NaN  NaN      NaN
50   GP;"F";16;"U";"LE3";"T";2;2;"services";"servic...  NaN  NaN      NaN
51   GP;"F";15;"U";"LE3";"T";4;2;"health";"other";"...  NaN  NaN      NaN
52   GP;"M";15;"U";"LE3";"A";4;2;"health";"health";...  NaN  NaN      NaN
53   GP;"F";15;"U";"GT3";"T";4;4;"services";"servic...  NaN  NaN      NaN
54   GP;"F";15;"U";"LE3";"A";3;3;"other";"other";"o...  NaN  NaN      NaN
55   GP;"F";16;"U";"GT3";"A";2;1;"other";"other";"o...  NaN  NaN      NaN
56   GP;"F";15;"U";"GT3";"A";4;3;"services";"servic...  NaN  NaN      NaN
57   GP;"M";15;"U";"GT3";"T";4;4;"teacher";"health"...  NaN  NaN      NaN
58   GP;"M";15;"U";"LE3";"T";1;2;"other";"at_home";...  NaN  NaN      NaN
59   GP;"F";16;"U";"GT3";"T";4;2;"services";"other"...  NaN  NaN      NaN
60   GP;"F";16;"R";"GT3";"T";4;4;"health";"teacher"...  NaN  NaN      NaN
61   GP;"F";16;"U";"GT3";"T";1;1;"services";"servic...  NaN  NaN      NaN
62   GP;"F";16;"U";"LE3";"T";1;2;"other";"services"...  NaN  NaN      NaN
63   GP;"F";16;"U";"GT3";"T";4;3;"teacher";"health"...  NaN  NaN      NaN
64   GP;"F";15;"U";"LE3";"T";4;3;"services";"servic...  NaN  NaN      NaN
65   GP;"F";16;"U";"LE3";"T";4;3;"teacher";"service...  NaN  NaN      NaN
66   GP;"M";15;"U";"GT3";"A";4;4;"other";"services"...  NaN  NaN      NaN
67   GP;"F";16;"U";"GT3";"T";3;1;"services";"other"...  NaN  NaN      NaN
68   GP;"F";15;"R";"LE3";"T";2;2;"health";"services...  NaN  NaN      NaN
69   GP;"F";15;"R";"LE3";"T";3;1;"other";"other";"r...  NaN  NaN      NaN
70   GP;"M";16;"U";"GT3";"T";3;1;"other";"other";"r...  NaN  NaN      NaN
71   GP;"M";15;"U";"GT3";"T";4;2;"other";"other";"c...  NaN  NaN      NaN
72   GP;"F";15;"R";"GT3";"T";1;1;"other";"other";"r...  NaN  NaN      NaN
73   GP;"M";16;"U";"GT3";"T";3;1;"other";"other";"r...  NaN  NaN      NaN
74   GP;"F";16;"U";"GT3";"T";3;3;"other";"services"...  NaN  NaN      NaN
75   GP;"M";15;"U";"GT3";"T";4;3;"teacher";"other";...  NaN  NaN      NaN
76   GP;"M";15;"U";"GT3";"T";4;0;"teacher";"other";...  NaN  NaN      NaN
77   GP;"F";16;"U";"GT3";"T";2;2;"other";"other";"r...  NaN  NaN      NaN
78   GP;"M";17;"U";"GT3";"T";2;1;"other";"other";"h...  NaN  NaN      NaN
79   GP;"F";16;"U";"GT3";"T";3;4;"at_home";"other";...  NaN  NaN      NaN
80   GP;"M";15;"U";"GT3";"T";2;3;"other";"services"...  NaN  NaN      NaN
81   GP;"M";15;"U";"GT3";"T";2;3;"other";"other";"h...  NaN  NaN      NaN
82   GP;"F";15;"U";"LE3";"T";3;2;"services";"other"...  NaN  NaN      NaN
83   GP;"M";15;"U";"LE3";"T";2;2;"services";"servic...  NaN  NaN      NaN
84   GP;"F";15;"U";"GT3";"T";1;1;"other";"other";"h...  NaN  NaN      NaN
85   GP;"F";15;"U";"GT3";"T";4;4;"services";"servic...  NaN  NaN      NaN
86   GP;"F";16;"U";"LE3";"T";2;2;"at_home";"other";...  NaN  NaN      NaN
87   GP;"F";15;"U";"GT3";"T";4;2;"other";"other";"r...  NaN  NaN      NaN
88   GP;"M";16;"U";"GT3";"T";2;2;"services";"other"...  NaN  NaN      NaN
89   GP;"M";16;"U";"LE3";"A";4;4;"teacher";"health"...  NaN  NaN      NaN
90   GP;"F";16;"U";"GT3";"T";3;3;"other";"other";"h...  NaN  NaN      NaN
91   GP;"F";15;"U";"GT3";"T";4;3;"services";"other"...  NaN  NaN      NaN
92   GP;"F";16;"U";"LE3";"T";3;1;"other";"other";"h...  NaN  NaN      NaN
93   GP;"F";16;"U";"GT3";"T";4;2;"teacher";"service...  NaN  NaN      NaN
94   GP;"M";15;"U";"LE3";"T";2;2;"services";"health...  NaN  NaN      NaN
95   GP;"F";15;"R";"GT3";"T";1;1;"at_home";"other";...  NaN  NaN      NaN
96   GP;"M";16;"R";"GT3";"T";4;3;"services";"other"...  NaN  NaN      NaN
97   GP;"F";16;"U";"GT3";"T";2;1;"other";"other";"c...  NaN  NaN      NaN
98   GP;"F";16;"U";"GT3";"T";4;4;"other";"other";"r...  NaN  NaN      NaN
99   GP;"F";16;"U";"GT3";"T";4;3;"other";"at_home";...  NaN  NaN      NaN
100  GP;"M";16;"U";"GT3";"T";4;4;"services";"servic...  NaN  NaN      NaN
101  GP;"M";16;"U";"GT3";"T";4;4;"services";"teache...  NaN  NaN      NaN
102  GP;"M";15;"U";"GT3";"T";4;4;"services";"other"...  NaN  NaN      NaN
103  GP;"F";15;"U";"GT3";"T";3;2;"services";"other"...  NaN  NaN      NaN
104  GP;"M";15;"U";"GT3";"A";3;4;"services";"other"...  NaN  NaN      NaN
105  GP;"F";15;"U";"GT3";"A";3;3;"other";"health";"...  NaN  NaN      NaN
106  GP;"F";15;"U";"GT3";"T";2;2;"other";"other";"c...  NaN  NaN      NaN
107  GP;"M";16;"U";"GT3";"T";3;3;"services";"other"...  NaN  NaN      NaN
108  GP;"M";15;"R";"GT3";"T";4;4;"other";"other";"h...  NaN  NaN      NaN
109  GP;"F";16;"U";"LE3";"T";4;4;"health";"health";...  NaN  NaN      NaN
110  GP;"M";15;"U";"LE3";"A";4;4;"teacher";"teacher...  NaN  NaN      NaN
111  GP;"F";16;"R";"GT3";"T";3;3;"services";"other"...  NaN  NaN      NaN
112  GP;"F";16;"U";"GT3";"T";2;2;"at_home";"other";...  NaN  NaN      NaN
113  GP;"M";15;"U";"LE3";"T";4;2;"teacher";"other";...  NaN  NaN      NaN
114  GP;"M";15;"R";"GT3";"T";2;1;"health";"services...  NaN  NaN      NaN
115  GP;"M";16;"U";"GT3";"T";4;4;"teacher";"teacher...  NaN  NaN      NaN
116  GP;"M";15;"U";"GT3";"T";4;4;"other";"teacher";...  NaN  NaN      NaN
117  GP;"M";16;"U";"GT3";"T";3;3;"other";"services"...  NaN  NaN      NaN
118  GP;"M";17;"R";"GT3";"T";1;3;"other";"other";"c...  NaN  NaN      NaN
119  GP;"M";15;"U";"GT3";"T";3;4;"other";"other";"r...  NaN  NaN      NaN
120  GP;"F";15;"U";"GT3";"T";1;2;"at_home";"service...  NaN  NaN      NaN
121  GP;"M";15;"U";"GT3";"T";2;2;"services";"servic...  NaN  NaN      NaN
122  GP;"F";16;"U";"LE3";"T";2;4;"other";"health";"...  NaN  NaN      NaN
123  GP;"M";16;"U";"GT3";"T";4;4;"health";"other";"...  NaN  NaN      NaN
124  GP;"F";16;"U";"GT3";"T";2;2;"other";"other";"h...  NaN  NaN      NaN
125  GP;"M";15;"U";"GT3";"T";3;4;"services";"servic...  NaN  NaN      NaN
126  GP;"F";15;"U";"LE3";"A";3;4;"other";"other";"h...  NaN  NaN      NaN
127  GP;"F";19;"U";"GT3";"T";0;1;"at_home";"other";...  NaN  NaN      NaN
128  GP;"M";18;"R";"GT3";"T";2;2;"services";"other"...  NaN  NaN      NaN
129  GP;"M";16;"R";"GT3";"T";4;4;"teacher";"teacher...  NaN  NaN      NaN
130  GP;"F";15;"R";"GT3";"T";3;4;"services";"teache...  NaN  NaN      NaN
131  GP;"F";15;"U";"GT3";"T";1;1;"at_home";"other";...  NaN  NaN      NaN
132  GP;"F";17;"U";"LE3";"T";2;2;"other";"other";"c...  NaN  NaN      NaN
133  GP;"F";16;"U";"GT3";"A";3;4;"services";"other"...  NaN  NaN      NaN
134  GP;"M";15;"R";"GT3";"T";3;4;"at_home";"teacher...  NaN  NaN      NaN
135  GP;"F";15;"U";"GT3";"T";4;4;"services";"at_hom...  NaN  NaN      NaN
136  GP;"M";17;"R";"GT3";"T";3;4;"at_home";"other";...  NaN  NaN      NaN
137  GP;"F";16;"U";"GT3";"A";3;3;"other";"other";"c...  NaN  NaN      NaN
138  GP;"M";16;"U";"LE3";"T";1;1;"services";"other"...  NaN  NaN      NaN
139  GP;"F";15;"U";"GT3";"T";4;4;"teacher";"teacher...  NaN  NaN      NaN
140  GP;"M";15;"U";"GT3";"T";4;3;"teacher";"service...  NaN  NaN      NaN
141  GP;"M";16;"U";"LE3";"T";2;2;"services";"servic...  NaN  NaN      NaN
142  GP;"F";15;"U";"GT3";"T";4;4;"teacher";"service...  NaN  NaN      NaN
143  GP;"F";16;"U";"LE3";"T";1;1;"at_home";"at_home...  NaN  NaN      NaN
144  GP;"M";17;"U";"GT3";"T";2;1;"other";"other";"h...  NaN  NaN      NaN
145  GP;"F";15;"U";"GT3";"T";1;1;"other";"services"...  NaN  NaN      NaN
146  GP;"F";15;"U";"GT3";"T";3;2;"health";"services...  NaN  NaN      NaN
147  GP;"F";15;"U";"GT3";"T";1;2;"at_home";"other";...  NaN  NaN      NaN
148  GP;"M";16;"U";"GT3";"T";4;4;"teacher";"teacher...  NaN  NaN      NaN
149  GP;"M";15;"U";"LE3";"A";2;1;"services";"other"...  NaN  NaN      NaN
150  GP;"M";18;"U";"LE3";"T";1;1;"other";"other";"c...  NaN  NaN      NaN
151  GP;"M";16;"U";"LE3";"T";2;1;"at_home";"other";...  NaN  NaN      NaN
152  GP;"F";15;"R";"GT3";"T";3;3;"services";"servic...  NaN  NaN      NaN
153  GP;"M";19;"U";"GT3";"T";3;2;"services";"at_hom...  NaN  NaN      NaN
154  GP;"F";17;"U";"GT3";"T";4;4;"other";"teacher";...  NaN  NaN      NaN
155  GP;"M";15;"R";"GT3";"T";2;3;"at_home";"service...  NaN  NaN      NaN
156  GP;"M";17;"R";"LE3";"T";1;2;"other";"other";"r...  NaN  NaN      NaN
157  GP;"F";18;"R";"GT3";"T";1;1;"at_home";"other";...  NaN  NaN      NaN
158  GP;"M";16;"R";"GT3";"T";2;2;"at_home";"other";...  NaN  NaN      NaN
159  GP;"M";16;"U";"GT3";"T";3;3;"other";"services"...  NaN  NaN      NaN
160  GP;"M";17;"R";"LE3";"T";2;1;"at_home";"other";...  NaN  NaN      NaN
161  GP;"M";15;"R";"GT3";"T";3;2;"other";"other";"c...  NaN  NaN      NaN
162  GP;"M";16;"U";"LE3";"T";1;2;"other";"other";"c...  NaN  NaN      NaN
163  GP;"M";17;"U";"GT3";"T";1;3;"at_home";"service...  NaN  NaN      NaN
164  GP;"M";17;"R";"LE3";"T";1;1;"other";"services"...  NaN  NaN      NaN
165  GP;"M";16;"U";"GT3";"T";3;2;"services";"servic...  NaN  NaN      NaN
166  GP;"M";16;"U";"GT3";"T";2;2;"other";"other";"c...  NaN  NaN      NaN
167  GP;"F";16;"U";"GT3";"T";4;2;"health";"services...  NaN  NaN      NaN
168  GP;"F";16;"U";"GT3";"T";2;2;"other";"other";"h...  NaN  NaN      NaN
169  GP;"F";16;"U";"GT3";"T";4;4;"health";"health";...  NaN  NaN      NaN
170  GP;"M";16;"U";"GT3";"T";3;4;"other";"other";"c...  NaN  NaN      NaN
171  GP;"M";16;"U";"GT3";"T";1;0;"other";"other";"r...  NaN  NaN      NaN
172  GP;"M";17;"U";"LE3";"T";4;4;"teacher";"other";...  NaN  NaN      NaN
173  GP;"F";16;"U";"GT3";"T";1;3;"at_home";"service...  NaN  NaN      NaN
174  GP;"F";16;"U";"LE3";"T";3;3;"other";"other";"r...  NaN  NaN      NaN
175  GP;"M";17;"U";"LE3";"T";4;3;"teacher";"other";...  NaN  NaN      NaN
176  GP;"F";16;"U";"GT3";"T";2;2;"services";"other"...  NaN  NaN      NaN
177  GP;"M";17;"U";"GT3";"T";3;3;"other";"other";"r...  NaN  NaN      NaN
178  GP;"M";16;"R";"GT3";"T";4;2;"teacher";"service...  NaN  NaN      NaN
179  GP;"M";17;"U";"GT3";"T";4;3;"other";"other";"c...  NaN  NaN      NaN
180  GP;"M";16;"U";"GT3";"T";4;3;"teacher";"other";...  NaN  NaN      NaN
181  GP;"M";16;"U";"GT3";"T";3;3;"services";"other"...  NaN  NaN      NaN
182  GP;"F";17;"U";"GT3";"T";2;4;"services";"servic...  NaN  NaN      NaN
183  GP;"F";17;"U";"LE3";"T";3;3;"other";"other";"r...  NaN  NaN      NaN
184  GP;"F";16;"U";"GT3";"T";3;2;"other";"other";"r...  NaN  NaN      NaN
185  GP;"M";17;"U";"GT3";"T";3;3;"services";"servic...  NaN  NaN      NaN
186  GP;"M";16;"U";"GT3";"T";1;2;"services";"servic...  NaN  NaN      NaN
187  GP;"M";16;"U";"LE3";"T";2;1;"other";"other";"c...  NaN  NaN      NaN
188  GP;"F";17;"U";"GT3";"A";3;3;"health";"other";"...  NaN  NaN      NaN
189  GP;"M";17;"R";"GT3";"T";1;2;"at_home";"other";...  NaN  NaN      NaN
190  GP;"F";16;"U";"GT3";"T";2;3;"services";"servic...  NaN  NaN      NaN
191  GP;"F";17;"U";"GT3";"T";1;1;"at_home";"service...  NaN  NaN      NaN
192  GP;"M";17;"U";"GT3";"T";1;2;"at_home";"service...  NaN  NaN      NaN
193  GP;"M";16;"R";"GT3";"T";3;3;"services";"servic...  NaN  NaN      NaN
194  GP;"M";16;"U";"GT3";"T";2;3;"other";"other";"h...  NaN  NaN      NaN
195  GP;"F";17;"U";"LE3";"T";2;4;"services";"servic...  NaN  NaN      NaN
196  GP;"M";17;"U";"GT3";"T";4;4;"services";"teache...  NaN  NaN      NaN
197  GP;"M";16;"R";"LE3";"T";3;3;"teacher";"other";...  NaN  NaN      NaN
198  GP;"F";17;"U";"GT3";"T";4;4;"services";"teache...  NaN  NaN      NaN
199  GP;"F";16;"U";"LE3";"T";4;4;"teacher";"teacher...  NaN  NaN      NaN
200  GP;"F";16;"U";"GT3";"T";4;3;"health";"other";"...  NaN  NaN      NaN
201  GP;"F";16;"U";"GT3";"T";2;3;"other";"other";"r...  NaN  NaN      NaN
202  GP;"F";17;"U";"GT3";"T";1;1;"other";"other";"c...  NaN  NaN      NaN
203  GP;"F";17;"R";"GT3";"T";2;2;"other";"other";"r...  NaN  NaN      NaN
204  GP;"F";16;"R";"GT3";"T";2;2;"services";"servic...  NaN  NaN      NaN
205  GP;"F";17;"U";"GT3";"T";3;4;"at_home";"service...  NaN  NaN      NaN
206  GP;"F";16;"U";"GT3";"A";3;1;"services";"other"...  NaN  NaN      NaN
207  GP;"F";16;"U";"GT3";"T";4;3;"teacher";"other";...  NaN  NaN      NaN
208  GP;"F";16;"U";"GT3";"T";1;1;"at_home";"other";...  NaN  NaN      NaN
209  GP;"F";17;"R";"GT3";"T";4;3;"teacher";"other";...  NaN  NaN      NaN
210  GP;"F";19;"U";"GT3";"T";3;3;"other";"other";"r...  NaN  NaN      NaN
211  GP;"M";17;"U";"LE3";"T";4;4;"services";"other"...  NaN  NaN      NaN
212  GP;"F";16;"U";"GT3";"A";2;2;"other";"other";"r...  NaN  NaN      NaN
213  GP;"M";18;"U";"GT3";"T";2;2;"services";"other"...  NaN  NaN      NaN
214  GP;"F";17;"R";"LE3";"T";4;4;"services";"other"...  NaN  NaN      NaN
215  GP;"F";17;"U";"LE3";"T";3;2;"other";"other";"r...  NaN  NaN      NaN
216  GP;"F";17;"U";"GT3";"T";4;3;"other";"other";"r...  NaN  NaN      NaN
217  GP;"M";18;"U";"LE3";"T";3;3;"services";"health...  NaN  NaN      NaN
218  GP;"F";17;"U";"GT3";"T";2;3;"at_home";"other";...  NaN  NaN      NaN
219  GP;"F";17;"U";"GT3";"T";2;2;"at_home";"at_home...  NaN  NaN      NaN
220  GP;"F";17;"R";"GT3";"T";2;1;"at_home";"service...  NaN  NaN      NaN
221  GP;"F";17;"U";"GT3";"T";1;1;"at_home";"other";...  NaN  NaN      NaN
222  GP;"F";16;"U";"GT3";"T";2;3;"services";"teache...  NaN  NaN      NaN
223  GP;"M";18;"U";"GT3";"T";2;2;"other";"other";"h...  NaN  NaN      NaN
224  GP;"F";16;"U";"GT3";"T";4;4;"teacher";"service...  NaN  NaN      NaN
225  GP;"F";18;"R";"GT3";"T";3;1;"other";"other";"r...  NaN  NaN      NaN
226  GP;"F";17;"U";"GT3";"T";3;2;"other";"other";"c...  NaN  NaN      NaN
227  GP;"M";17;"U";"LE3";"T";2;3;"services";"servic...  NaN  NaN      NaN
228  GP;"M";18;"U";"LE3";"T";2;1;"at_home";"other";...  NaN  NaN      NaN
229  GP;"F";17;"U";"GT3";"A";2;1;"other";"other";"c...  NaN  NaN      NaN
230  GP;"F";17;"U";"LE3";"T";4;3;"health";"other";"...  NaN  NaN      NaN
231  GP;"M";17;"R";"GT3";"T";2;2;"other";"other";"c...  NaN  NaN      NaN
232  GP;"M";17;"U";"GT3";"T";4;4;"teacher";"teacher...  NaN  NaN      NaN
233  GP;"M";16;"U";"GT3";"T";4;4;"health";"other";"...  NaN  NaN      NaN
234  GP;"M";16;"U";"LE3";"T";1;1;"other";"other";"h...  NaN  NaN      NaN
235  GP;"M";16;"U";"GT3";"T";3;2;"at_home";"other";...  NaN  NaN      NaN
236  GP;"M";17;"U";"LE3";"T";2;2;"other";"other";"h...  NaN  NaN      NaN
237  GP;"F";16;"U";"GT3";"T";2;1;"other";"other";"h...  NaN  NaN      NaN
238  GP;"F";17;"R";"GT3";"T";2;1;"at_home";"service...  NaN  NaN      NaN
239  GP;"M";18;"U";"GT3";"T";2;2;"other";"services"...  NaN  NaN      NaN
240  GP;"M";17;"U";"LE3";"T";4;3;"health";"other";"...  NaN  NaN      NaN
241  GP;"M";17;"R";"LE3";"A";4;4;"teacher";"other";...  NaN  NaN      NaN
242  GP;"M";16;"U";"LE3";"T";4;3;"teacher";"other";...  NaN  NaN      NaN
243  GP;"M";16;"U";"GT3";"T";4;4;"services";"servic...  NaN  NaN      NaN
244  GP;"F";18;"U";"GT3";"T";2;1;"other";"other";"c...  NaN  NaN      NaN
245  GP;"M";16;"U";"GT3";"T";2;1;"other";"other";"c...  NaN  NaN      NaN
246  GP;"M";17;"U";"GT3";"T";2;3;"other";"other";"c...  NaN  NaN      NaN
247  GP;"M";22;"U";"GT3";"T";3;1;"services";"servic...  NaN  NaN      NaN
248  GP;"M";18;"R";"LE3";"T";3;3;"other";"services"...  NaN  NaN      NaN
249  GP;"M";16;"U";"GT3";"T";0;2;"other";"other";"o...  NaN  NaN      NaN
250  GP;"M";18;"U";"GT3";"T";3;2;"services";"other"...  NaN  NaN      NaN
251  GP;"M";16;"U";"GT3";"T";3;3;"at_home";"other";...  NaN  NaN      NaN
252  GP;"M";18;"U";"GT3";"T";2;1;"services";"servic...  NaN  NaN      NaN
253  GP;"M";16;"R";"GT3";"T";2;1;"other";"other";"c...  NaN  NaN      NaN
254  GP;"M";17;"R";"GT3";"T";2;1;"other";"other";"c...  NaN  NaN      NaN
255  GP;"M";17;"U";"LE3";"T";1;1;"health";"other";"...  NaN  NaN      NaN
256  GP;"F";17;"U";"LE3";"T";4;2;"teacher";"service...  NaN  NaN      NaN
257  GP;"M";19;"U";"LE3";"A";4;3;"services";"at_hom...  NaN  NaN      NaN
258  GP;"M";18;"U";"GT3";"T";2;1;"other";"other";"h...  NaN  NaN      NaN
259  GP;"F";17;"U";"LE3";"T";2;2;"services";"servic...  NaN  NaN      NaN
260  GP;"F";18;"U";"GT3";"T";4;3;"services";"other"...  NaN  NaN      NaN
261  GP;"M";18;"U";"GT3";"T";4;3;"teacher";"other";...  NaN  NaN      NaN
262  GP;"M";18;"R";"GT3";"T";3;2;"other";"other";"c...  NaN  NaN      NaN
263  GP;"F";17;"U";"GT3";"T";3;3;"other";"other";"h...  NaN  NaN      NaN
264  GP;"F";18;"U";"GT3";"T";2;2;"at_home";"service...  NaN  NaN      NaN
265  GP;"M";18;"R";"LE3";"A";3;4;"other";"other";"r...  NaN  NaN      NaN
266  GP;"M";17;"U";"GT3";"T";3;1;"services";"other"...  NaN  NaN      NaN
267  GP;"F";18;"R";"GT3";"T";4;4;"teacher";"other";...  NaN  NaN      NaN
268  GP;"M";18;"U";"GT3";"T";4;2;"health";"other";"...  NaN  NaN      NaN

In [9]:
df.head()
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 395 entries, 0 to 394
Data columns (total 33 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   school      395 non-null    object
 1   sex         0 non-null      float64
 2   age         0 non-null      float64
 3   address     0 non-null      float64
 4   famsize     0 non-null      float64
 5   Pstatus     0 non-null      float64
 6   Medu        0 non-null      float64
 7   Fedu        0 non-null      float64
 8   Mjob        0 non-null      float64
 9   Fjob        0 non-null      float64
 10  reason      0 non-null      float64
 11  guardian    0 non-null      float64
 12  traveltime  0 non-null      float64
 13  studytime   0 non-null      float64
 14  failures    0 non-null      float64
 15  schoolsup   0 non-null      float64
 16  famsup      0 non-null      float64
 17  paid        0 non-null      float64
 18  activities  0 non-null      float64
 19  nursery     0 non-null      float64
 20  higher      0 non-null      float64
 21  internet    0 non-null      float64
 22  romantic    0 non-null      float64
 23  famrel      0 non-null      float64
 24  freetime    0 non-null      float64
 25  goout       0 non-null      float64
 26  Dalc        0 non-null      float64
 27  Walc        0 non-null      float64
 28  health      0 non-null      float64
 29  absences    0 non-null      float64
 30  G1          0 non-null      float64
 31  G2          0 non-null      float64
 32  G3          0 non-null      float64
dtypes: float64(32), object(1)
memory usage: 102.0+ KB

,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,guardian,traveltime,studytime,failures,schoolsup,famsup,paid,activities,nursery,higher,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
count,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### ***DATA CLEANING

##### Check Missing Values

In [10]:
df.isnull().sum()

school          0
sex           395
age           395
address       395
famsize       395
Pstatus       395
Medu          395
Fedu          395
Mjob          395
Fjob          395
reason        395
guardian      395
traveltime    395
studytime     395
failures      395
schoolsup     395
famsup        395
paid          395
activities    395
nursery       395
higher        395
internet      395
romantic      395
famrel        395
freetime      395
goout         395
Dalc          395
Walc          395
health        395
absences      395
G1            395
G2            395
G3            395
dtype: int64

In [11]:
df = pd.read_csv("student-mat.csv" , sep=';')

In [12]:
df = df[df.columns[0]].str.split(';', expand=True)

In [13]:
df = df[df.columns[0]].str.split(',', expand=True)

In [14]:
df.columns = df.iloc[0]
df = df[1:]

In [15]:
df.head()

0  GP
1  GP
2  GP
3  GP
4  GP
5  GP

## Handle Missing Values

In [16]:
print(df.columns)

Index(['GP'], dtype='object', name=0)

In [17]:
data = pd.read_csv("student-mat.csv", sep=';')
print(data.head())
print(data.columns)

                                              school  sex  age  address  \
0  GP;"F";18;"U";"GT3";"A";4;4;"at_home";"teacher...  NaN  NaN      NaN
1  GP;"F";17;"U";"GT3";"T";1;1;"at_home";"other";...  NaN  NaN      NaN
2  GP;"F";15;"U";"LE3";"T";1;1;"at_home";"other";...  NaN  NaN      NaN
3  GP;"F";15;"U";"GT3";"T";4;2;"health";"services...  NaN  NaN      NaN
4  GP;"F";16;"U";"GT3";"T";3;3;"other";"other";"h...  NaN  NaN      NaN

   famsize  Pstatus  Medu  Fedu  Mjob  Fjob  reason  guardian  traveltime  \
0      NaN      NaN   NaN   NaN   NaN   NaN     NaN       NaN         NaN
1      NaN      NaN   NaN   NaN   NaN   NaN     NaN       NaN         NaN
2      NaN      NaN   NaN   NaN   NaN   NaN     NaN       NaN         NaN
3      NaN      NaN   NaN   NaN   NaN   NaN     NaN       NaN         NaN
4      NaN      NaN   NaN   NaN   NaN   NaN     NaN       NaN         NaN

   studytime  failures  schoolsup  famsup  paid  activities  nursery  higher  \
0        NaN       NaN        NaN     NaN   NaN         NaN      NaN     NaN
1        NaN       NaN        NaN     NaN   NaN         NaN      NaN     NaN
2        NaN       NaN        NaN     NaN   NaN         NaN      NaN     NaN
3        NaN       NaN        NaN     NaN   NaN         NaN      NaN     NaN
4        NaN       NaN        NaN     NaN   NaN         NaN      NaN     NaN

   internet  romantic  famrel  freetime  goout  Dalc  Walc  health  absences  \
0       NaN       NaN     NaN       NaN    NaN   NaN   NaN     NaN       NaN
1       NaN       NaN     NaN       NaN    NaN   NaN   NaN     NaN       NaN
2       NaN       NaN     NaN       NaN    NaN   NaN   NaN     NaN       NaN
3       NaN       NaN     NaN       NaN    NaN   NaN   NaN     NaN       NaN
4       NaN       NaN     NaN       NaN    NaN   NaN   NaN     NaN       NaN

   G1  G2  G3
0 NaN NaN NaN
1 NaN NaN NaN
2 NaN NaN NaN
3 NaN NaN NaN
4 NaN NaN NaN
Index(['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu',
       'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime', 'studytime',
       'failures', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery',
       'higher', 'internet', 'romantic', 'famrel', 'freetime', 'goout', 'Dalc',
       'Walc', 'health', 'absences', 'G1', 'G2', 'G3'],
      dtype='object')

#### Discard rows

In [18]:
data = data.dropna()

#### OUTLIER DETECTION

In [19]:
print(data.columns)

Index(['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu',
       'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime', 'studytime',
       'failures', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery',
       'higher', 'internet', 'romantic', 'famrel', 'freetime', 'goout', 'Dalc',
       'Walc', 'health', 'absences', 'G1', 'G2', 'G3'],
      dtype='object')

In [20]:
data.columns = data.columns.str.strip()
print(data.columns)

Index(['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu',
       'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime', 'studytime',
       'failures', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery',
       'higher', 'internet', 'romantic', 'famrel', 'freetime', 'goout', 'Dalc',
       'Walc', 'health', 'absences', 'G1', 'G2', 'G3'],
      dtype='object')

In [21]:
print(data.columns.tolist())

['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu', 'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime', 'studytime', 'failures', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery', 'higher', 'internet', 'romantic', 'famrel', 'freetime', 'goout', 'Dalc', 'Walc', 'health', 'absences', 'G1', 'G2', 'G3']

In [22]:
print(data.columns.tolist())

['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu', 'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime', 'studytime', 'failures', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery', 'higher', 'internet', 'romantic', 'famrel', 'freetime', 'goout', 'Dalc', 'Walc', 'health', 'absences', 'G1', 'G2', 'G3']

In [23]:
print(data.columns.tolist())

['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu', 'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime', 'studytime', 'failures', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery', 'higher', 'internet', 'romantic', 'famrel', 'freetime', 'goout', 'Dalc', 'Walc', 'health', 'absences', 'G1', 'G2', 'G3']

In [24]:
data = pd.read_csv("student-mat.csv", sep=';')
print(data.head())
print(data.columns.tolist())

                                              school  sex  age  address  \
0  GP;"F";18;"U";"GT3";"A";4;4;"at_home";"teacher...  NaN  NaN      NaN
1  GP;"F";17;"U";"GT3";"T";1;1;"at_home";"other";...  NaN  NaN      NaN
2  GP;"F";15;"U";"LE3";"T";1;1;"at_home";"other";...  NaN  NaN      NaN
3  GP;"F";15;"U";"GT3";"T";4;2;"health";"services...  NaN  NaN      NaN
4  GP;"F";16;"U";"GT3";"T";3;3;"other";"other";"h...  NaN  NaN      NaN

   famsize  Pstatus  Medu  Fedu  Mjob  Fjob  reason  guardian  traveltime  \
0      NaN      NaN   NaN   NaN   NaN   NaN     NaN       NaN         NaN
1      NaN      NaN   NaN   NaN   NaN   NaN     NaN       NaN         NaN
2      NaN      NaN   NaN   NaN   NaN   NaN     NaN       NaN         NaN
3      NaN      NaN   NaN   NaN   NaN   NaN     NaN       NaN         NaN
4      NaN      NaN   NaN   NaN   NaN   NaN     NaN       NaN         NaN

   studytime  failures  schoolsup  famsup  paid  activities  nursery  higher  \
0        NaN       NaN        NaN     NaN   NaN         NaN      NaN     NaN
1        NaN       NaN        NaN     NaN   NaN         NaN      NaN     NaN
2        NaN       NaN        NaN     NaN   NaN         NaN      NaN     NaN
3        NaN       NaN        NaN     NaN   NaN         NaN      NaN     NaN
4        NaN       NaN        NaN     NaN   NaN         NaN      NaN     NaN

   internet  romantic  famrel  freetime  goout  Dalc  Walc  health  absences  \
0       NaN       NaN     NaN       NaN    NaN   NaN   NaN     NaN       NaN
1       NaN       NaN     NaN       NaN    NaN   NaN   NaN     NaN       NaN
2       NaN       NaN     NaN       NaN    NaN   NaN   NaN     NaN       NaN
3       NaN       NaN     NaN       NaN    NaN   NaN   NaN     NaN       NaN
4       NaN       NaN     NaN       NaN    NaN   NaN   NaN     NaN       NaN

   G1  G2  G3
0 NaN NaN NaN
1 NaN NaN NaN
2 NaN NaN NaN
3 NaN NaN NaN
4 NaN NaN NaN
['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu', 'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime', 'studytime', 'failures', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery', 'higher', 'internet', 'romantic', 'famrel', 'freetime', 'goout', 'Dalc', 'Walc', 'health', 'absences', 'G1', 'G2', 'G3']

In [25]:
print(data.shape)
print(data.head())
print(data.columns)
print(data.info())

(395, 33)
                                              school  sex  age  address  \
0  GP;"F";18;"U";"GT3";"A";4;4;"at_home";"teacher...  NaN  NaN      NaN
1  GP;"F";17;"U";"GT3";"T";1;1;"at_home";"other";...  NaN  NaN      NaN
2  GP;"F";15;"U";"LE3";"T";1;1;"at_home";"other";...  NaN  NaN      NaN
3  GP;"F";15;"U";"GT3";"T";4;2;"health";"services...  NaN  NaN      NaN
4  GP;"F";16;"U";"GT3";"T";3;3;"other";"other";"h...  NaN  NaN      NaN

   famsize  Pstatus  Medu  Fedu  Mjob  Fjob  reason  guardian  traveltime  \
0      NaN      NaN   NaN   NaN   NaN   NaN     NaN       NaN         NaN
1      NaN      NaN   NaN   NaN   NaN   NaN     NaN       NaN         NaN
2      NaN      NaN   NaN   NaN   NaN   NaN     NaN       NaN         NaN
3      NaN      NaN   NaN   NaN   NaN   NaN     NaN       NaN         NaN
4      NaN      NaN   NaN   NaN   NaN   NaN     NaN       NaN         NaN

   studytime  failures  schoolsup  famsup  paid  activities  nursery  higher  \
0        NaN       NaN        NaN     NaN   NaN         NaN      NaN     NaN
1        NaN       NaN        NaN     NaN   NaN         NaN      NaN     NaN
2        NaN       NaN        NaN     NaN   NaN         NaN      NaN     NaN
3        NaN       NaN        NaN     NaN   NaN         NaN      NaN     NaN
4        NaN       NaN        NaN     NaN   NaN         NaN      NaN     NaN

   internet  romantic  famrel  freetime  goout  Dalc  Walc  health  absences  \
0       NaN       NaN     NaN       NaN    NaN   NaN   NaN     NaN       NaN
1       NaN       NaN     NaN       NaN    NaN   NaN   NaN     NaN       NaN
2       NaN       NaN     NaN       NaN    NaN   NaN   NaN     NaN       NaN
3       NaN       NaN     NaN       NaN    NaN   NaN   NaN     NaN       NaN
4       NaN       NaN     NaN       NaN    NaN   NaN   NaN     NaN       NaN

   G1  G2  G3
0 NaN NaN NaN
1 NaN NaN NaN
2 NaN NaN NaN
3 NaN NaN NaN
4 NaN NaN NaN
Index(['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu',
       'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime', 'studytime',
       'failures', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery',
       'higher', 'internet', 'romantic', 'famrel', 'freetime', 'goout', 'Dalc',
       'Walc', 'health', 'absences', 'G1', 'G2', 'G3'],
      dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 395 entries, 0 to 394
Data columns (total 33 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   school      395 non-null    object
 1   sex         0 non-null      float64
 2   age         0 non-null      float64
 3   address     0 non-null      float64
 4   famsize     0 non-null      float64
 5   Pstatus     0 non-null      float64
 6   Medu        0 non-null      float64
 7   Fedu        0 non-null      float64
 8   Mjob        0 non-null      float64
 9   Fjob        0 non-null      float64
 10  reason      0 non-null      float64
 11  guardian    0 non-null      float64
 12  traveltime  0 non-null      float64
 13  studytime   0 non-null      float64
 14  failures    0 non-null      float64
 15  schoolsup   0 non-null      float64
 16  famsup      0 non-null      float64
 17  paid        0 non-null      float64
 18  activities  0 non-null      float64
 19  nursery     0 non-null      float64
 20  higher      0 non-null      float64
 21  internet    0 non-null      float64
 22  romantic    0 non-null      float64
 23  famrel      0 non-null      float64
 24  freetime    0 non-null      float64
 25  goout       0 non-null      float64
 26  Dalc        0 non-null      float64
 27  Walc        0 non-null      float64
 28  health      0 non-null      float64
 29  absences    0 non-null      float64
 30  G1          0 non-null      float64
 31  G2          0 non-null      float64
 32  G3          0 non-null      float64
dtypes: float64(32), object(1)
memory usage: 102.0+ KB
None

In [26]:
data.isnull().sum()

school          0
sex           395
age           395
address       395
famsize       395
Pstatus       395
Medu          395
Fedu          395
Mjob          395
Fjob          395
reason        395
guardian      395
traveltime    395
studytime     395
failures      395
schoolsup     395
famsup        395
paid          395
activities    395
nursery       395
higher        395
internet      395
romantic      395
famrel        395
freetime      395
goout         395
Dalc          395
Walc          395
health        395
absences      395
G1            395
G2            395
G3            395
dtype: int64

In [27]:
print(data.columns.tolist())

['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu', 'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime', 'studytime', 'failures', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery', 'higher', 'internet', 'romantic', 'famrel', 'freetime', 'goout', 'Dalc', 'Walc', 'health', 'absences', 'G1', 'G2', 'G3']

In [28]:
data.shape

(395, 33)

In [29]:
data.duplicated().sum()

np.int64(0)

In [30]:
data.drop_duplicates(inplace=True)

In [31]:
data.duplicated().sum()

np.int64(0)

In [32]:
data.isnull().sum()

school          0
sex           395
age           395
address       395
famsize       395
Pstatus       395
Medu          395
Fedu          395
Mjob          395
Fjob          395
reason        395
guardian      395
traveltime    395
studytime     395
failures      395
schoolsup     395
famsup        395
paid          395
activities    395
nursery       395
higher        395
internet      395
romantic      395
famrel        395
freetime      395
goout         395
Dalc          395
Walc          395
health        395
absences      395
G1            395
G2            395
G3            395
dtype: int64

In [33]:
import numpy as np
import pandas as pd
import re
import string
import pickle

In [34]:
def remove_punctuations(text):
    for punctuation in string.punctuation:
        text = text.replace(punctuation, '')
    return text

In [35]:
import pandas as pd

data = pd.read_csv('student-mat.csv')
data.head()

  school;sex;age;address;famsize;Pstatus;Medu;Fedu;Mjob;Fjob;reason;guardian;traveltime;studytime;failures;schoolsup;famsup;paid;activities;nursery;higher;internet;romantic;famrel;freetime;goout;Dalc;Walc;health;absences;G1;G2;G3
0  GP;"F";18;"U";"GT3";"A";4;4;"at_home";"teacher...
1  GP;"F";17;"U";"GT3";"T";1;1;"at_home";"other";...
2  GP;"F";15;"U";"LE3";"T";1;1;"at_home";"other";...
3  GP;"F";15;"U";"GT3";"T";4;2;"health";"services...
4  GP;"F";16;"U";"GT3";"T";3;3;"other";"other";"h...

In [36]:
pip install nltk

Requirement already satisfied: nltk in c:\users\user\documents\myproject\datamining\data_mining_project2\data_mining_student_performance\env\lib\site-packages (3.9.3)
Requirement already satisfied: click in c:\users\user\documents\myproject\datamining\data_mining_project2\data_mining_student_performance\env\lib\site-packages (from nltk) (8.3.1)
Requirement already satisfied: joblib in c:\users\user\documents\myproject\datamining\data_mining_project2\data_mining_student_performance\env\lib\site-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in c:\users\user\documents\myproject\datamining\data_mining_project2\data_mining_student_performance\env\lib\site-packages (from nltk) (2026.2.19)
Requirement already satisfied: tqdm in c:\users\user\documents\myproject\datamining\data_mining_project2\data_mining_student_performance\env\lib\site-packages (from nltk) (4.67.3)
Requirement already satisfied: colorama in c:\users\user\documents\myproject\datamining\data_mining_project2\data_mining_student_performance\env\lib\site-packages (from click->nltk) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

In [37]:
from nltk.stem import PorterStemmer
ps = PorterStemmer()

In [38]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\User\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [39]:
pip list

Package                   VersionNote: you may need to restart the kernel to use updated packages.

------------------------- -----------
anyio                     4.12.1
argon2-cffi               25.1.0
argon2-cffi-bindings      25.1.0
arrow                     1.4.0
asttokens                 3.0.1
async-lru                 2.2.0
attrs                     25.4.0
babel                     2.18.0
beautifulsoup4            4.14.3
bleach                    6.3.0
certifi                   2026.1.4
cffi                      2.0.0
charset-normalizer        3.4.4
click                     8.3.1
colorama                  0.4.6
comm                      0.2.3
contourpy                 1.3.2
cycler                    0.12.1
debugpy                   1.8.20
decorator                 5.2.1
defusedxml                0.7.1
exceptiongroup            1.3.1
executing                 2.2.1
fastjsonschema            2.21.2
fonttools                 4.61.1
fqdn                      1.5.1
h11                       0.16.0
httpcore                  1.0.9
httpx                     0.28.1
idna                      3.11
ipykernel                 7.2.0
ipython                   8.38.0
ipywidgets                8.1.8
isoduration               20.11.0
jedi                      0.19.2
Jinja2                    3.1.6
joblib                    1.5.3
json5                     0.13.0
jsonpointer               3.0.0
jsonschema                4.26.0
jsonschema-specifications 2025.9.1
jupyter                   1.1.1
jupyter_client            8.8.0
jupyter-console           6.6.3
jupyter_core              5.9.1
jupyter-events            0.12.0
jupyter-lsp               2.3.0
jupyter_server            2.17.0
jupyter_server_terminals  0.5.4
jupyterlab                4.5.4
jupyterlab_pygments       0.3.0
jupyterlab_server         2.28.0
jupyterlab_widgets        3.0.16
kiwisolver                1.4.9
lark                      1.3.1
MarkupSafe                3.0.3
matplotlib                3.10.8
matplotlib-inline         0.2.1
mistune                   3.2.0
nbclient                  0.10.4
nbconvert                 7.17.0
nbformat                  5.10.4
nest-asyncio              1.6.0
nltk                      3.9.3
notebook                  7.5.3
notebook_shim             0.2.4
numpy                     2.2.6
overrides                 7.7.0
packaging                 26.0
pandas                    2.3.3
pandocfilters             1.5.1
parso                     0.8.6
pillow                    12.1.1
pip                       26.0.1
platformdirs              4.9.2
prometheus_client         0.24.1
prompt_toolkit            3.0.52
psutil                    7.2.2
pure_eval                 0.2.3
pycparser                 3.0
Pygments                  2.19.2
pyparsing                 3.3.2
python-dateutil           2.9.0.post0
python-json-logger        4.0.0
pytz                      2025.2
pywinpty                  3.0.3
PyYAML                    6.0.3
pyzmq                     27.1.0
referencing               0.37.0
regex                     2026.2.19
requests                  2.32.5
rfc3339-validator         0.1.4
rfc3986-validator         0.1.1
rfc3987-syntax            1.1.0
rpds-py                   0.30.0
scikit-learn              1.7.2
scipy                     1.15.3
seaborn                   0.13.2
Send2Trash                2.1.0
setuptools                82.0.0
six                       1.17.0
soupsieve                 2.8.3
stack-data                0.6.3
terminado                 0.18.1
threadpoolctl             3.6.0
tinycss2                  1.4.0
tomli                     2.4.0
tornado                   6.5.4
tqdm                      4.67.3
traitlets                 5.14.3
typing_extensions         4.15.0
tzdata                    2025.3
uri-template              1.3.0
urllib3                   2.6.3
wcwidth                   0.6.0
webcolors                 25.10.0
webencodings              0.5.1
websocket-client          1.9.0
widgetsnbextension        4.0.15

In [40]:
import re
import string

In [41]:
print(data.columns)

Index(['school;sex;age;address;famsize;Pstatus;Medu;Fedu;Mjob;Fjob;reason;guardian;traveltime;studytime;failures;schoolsup;famsup;paid;activities;nursery;higher;internet;romantic;famrel;freetime;goout;Dalc;Walc;health;absences;G1;G2;G3'], dtype='object')

In [42]:
data.columns = data.columns.str.strip()

In [43]:
print(data.columns.tolist())

['school;sex;age;address;famsize;Pstatus;Medu;Fedu;Mjob;Fjob;reason;guardian;traveltime;studytime;failures;schoolsup;famsup;paid;activities;nursery;higher;internet;romantic;famrel;freetime;goout;Dalc;Walc;health;absences;G1;G2;G3']

In [44]:
print(data.head())

  school;sex;age;address;famsize;Pstatus;Medu;Fedu;Mjob;Fjob;reason;guardian;traveltime;studytime;failures;schoolsup;famsup;paid;activities;nursery;higher;internet;romantic;famrel;freetime;goout;Dalc;Walc;health;absences;G1;G2;G3
0  GP;"F";18;"U";"GT3";"A";4;4;"at_home";"teacher...
1  GP;"F";17;"U";"GT3";"T";1;1;"at_home";"other";...
2  GP;"F";15;"U";"LE3";"T";1;1;"at_home";"other";...
3  GP;"F";15;"U";"GT3";"T";4;2;"health";"services...
4  GP;"F";16;"U";"GT3";"T";3;3;"other";"other";"h...

In [45]:
import pandas as pd


columns = ["school","sex","age","address","famsize","Pstatus","Medu","Fedu",
           "Mjob","Fjob","reason","guardian","traveltime","studytime",
           "failures","schoolsup","famsup","paid","activities","nursery",
           "higher","internet","romantic","famrel","freetime","goout",
           "Dalc","Walc","health","absences","G1","G2","G3"]


data = pd.read_csv("student-mat.csv", sep=";", header=None, names=columns)


print(data.head())
print(data.shape)

                                              school  sex  age  address  \
0                                             school  sex  age  address
1  GP;"F";18;"U";"GT3";"A";4;4;"at_home";"teacher...  NaN  NaN      NaN
2  GP;"F";17;"U";"GT3";"T";1;1;"at_home";"other";...  NaN  NaN      NaN
3  GP;"F";15;"U";"LE3";"T";1;1;"at_home";"other";...  NaN  NaN      NaN
4  GP;"F";15;"U";"GT3";"T";4;2;"health";"services...  NaN  NaN      NaN

   famsize  Pstatus  Medu  Fedu  Mjob  Fjob  reason  guardian  traveltime  \
0  famsize  Pstatus  Medu  Fedu  Mjob  Fjob  reason  guardian  traveltime
1      NaN      NaN   NaN   NaN   NaN   NaN     NaN       NaN         NaN
2      NaN      NaN   NaN   NaN   NaN   NaN     NaN       NaN         NaN
3      NaN      NaN   NaN   NaN   NaN   NaN     NaN       NaN         NaN
4      NaN      NaN   NaN   NaN   NaN   NaN     NaN       NaN         NaN

   studytime  failures  schoolsup  famsup  paid  activities  nursery  higher  \
0  studytime  failures  schoolsup  famsup  paid  activities  nursery  higher
1        NaN       NaN        NaN     NaN   NaN         NaN      NaN     NaN
2        NaN       NaN        NaN     NaN   NaN         NaN      NaN     NaN
3        NaN       NaN        NaN     NaN   NaN         NaN      NaN     NaN
4        NaN       NaN        NaN     NaN   NaN         NaN      NaN     NaN

   internet  romantic  famrel  freetime  goout  Dalc  Walc  health  absences  \
0  internet  romantic  famrel  freetime  goout  Dalc  Walc  health  absences
1       NaN       NaN     NaN       NaN    NaN   NaN   NaN     NaN       NaN
2       NaN       NaN     NaN       NaN    NaN   NaN   NaN     NaN       NaN
3       NaN       NaN     NaN       NaN    NaN   NaN   NaN     NaN       NaN
4       NaN       NaN     NaN       NaN    NaN   NaN   NaN     NaN       NaN

    G1   G2   G3
0   G1   G2   G3
1  NaN  NaN  NaN
2  NaN  NaN  NaN
3  NaN  NaN  NaN
4  NaN  NaN  NaN
(396, 33)

In [46]:
import pandas as pd


columns = ["school","sex","age","address","famsize","Pstatus","Medu","Fedu",
           "Mjob","Fjob","reason","guardian","traveltime","studytime",
           "failures","schoolsup","famsup","paid","activities","nursery",
           "higher","internet","romantic","famrel","freetime","goout",
           "Dalc","Walc","health","absences","G1","G2","G3"]


data = pd.read_csv("student-mat.csv", sep=";", names=columns, header=0)


data = data.iloc[1:].reset_index(drop=True)

print(data.head())

                                              school  sex  age  address  \
0  GP;"F";17;"U";"GT3";"T";1;1;"at_home";"other";...  NaN  NaN      NaN
1  GP;"F";15;"U";"LE3";"T";1;1;"at_home";"other";...  NaN  NaN      NaN
2  GP;"F";15;"U";"GT3";"T";4;2;"health";"services...  NaN  NaN      NaN
3  GP;"F";16;"U";"GT3";"T";3;3;"other";"other";"h...  NaN  NaN      NaN
4  GP;"M";16;"U";"LE3";"T";4;3;"services";"other"...  NaN  NaN      NaN

   famsize  Pstatus  Medu  Fedu  Mjob  Fjob  reason  guardian  traveltime  \
0      NaN      NaN   NaN   NaN   NaN   NaN     NaN       NaN         NaN
1      NaN      NaN   NaN   NaN   NaN   NaN     NaN       NaN         NaN
2      NaN      NaN   NaN   NaN   NaN   NaN     NaN       NaN         NaN
3      NaN      NaN   NaN   NaN   NaN   NaN     NaN       NaN         NaN
4      NaN      NaN   NaN   NaN   NaN   NaN     NaN       NaN         NaN

   studytime  failures  schoolsup  famsup  paid  activities  nursery  higher  \
0        NaN       NaN        NaN     NaN   NaN         NaN      NaN     NaN
1        NaN       NaN        NaN     NaN   NaN         NaN      NaN     NaN
2        NaN       NaN        NaN     NaN   NaN         NaN      NaN     NaN
3        NaN       NaN        NaN     NaN   NaN         NaN      NaN     NaN
4        NaN       NaN        NaN     NaN   NaN         NaN      NaN     NaN

   internet  romantic  famrel  freetime  goout  Dalc  Walc  health  absences  \
0       NaN       NaN     NaN       NaN    NaN   NaN   NaN     NaN       NaN
1       NaN       NaN     NaN       NaN    NaN   NaN   NaN     NaN       NaN
2       NaN       NaN     NaN       NaN    NaN   NaN   NaN     NaN       NaN
3       NaN       NaN     NaN       NaN    NaN   NaN   NaN     NaN       NaN
4       NaN       NaN     NaN       NaN    NaN   NaN   NaN     NaN       NaN

   G1  G2  G3
0 NaN NaN NaN
1 NaN NaN NaN
2 NaN NaN NaN
3 NaN NaN NaN
4 NaN NaN NaN

In [47]:
print(data.columns)
print(data.shape)

Index(['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu',
       'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime', 'studytime',
       'failures', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery',
       'higher', 'internet', 'romantic', 'famrel', 'freetime', 'goout', 'Dalc',
       'Walc', 'health', 'absences', 'G1', 'G2', 'G3'],
      dtype='object')
(394, 33)

In [49]:
import pandas as pd


columns = ["school","sex","age","address","famsize","Pstatus","Medu","Fedu",
           "Mjob","Fjob","reason","guardian","traveltime","studytime",
           "failures","schoolsup","famsup","paid","activities","nursery",
           "higher","internet","romantic","famrel","freetime","goout",
           "Dalc","Walc","health","absences","G1","G2","G3"]


data = pd.read_csv("student-mat.csv", header=None)

data = data[0].str.split(";", expand=True)

data.columns = columns

data = data.replace('"', '', regex=True)

print(data.head())

   school  sex  age  address  famsize  Pstatus  Medu  Fedu     Mjob      Fjob  \
0  school  sex  age  address  famsize  Pstatus  Medu  Fedu     Mjob      Fjob
1      GP    F   18        U      GT3        A     4     4  at_home   teacher
2      GP    F   17        U      GT3        T     1     1  at_home     other
3      GP    F   15        U      LE3        T     1     1  at_home     other
4      GP    F   15        U      GT3        T     4     2   health  services

   reason  guardian  traveltime  studytime  failures  schoolsup  famsup  paid  \
0  reason  guardian  traveltime  studytime  failures  schoolsup  famsup  paid
1  course    mother           2          2         0        yes      no    no
2  course    father           1          2         0         no     yes    no
3   other    mother           1          2         3        yes      no   yes
4    home    mother           1          3         0         no     yes   yes

   activities  nursery  higher  internet  romantic  famrel  freetime  goout  \
0  activities  nursery  higher  internet  romantic  famrel  freetime  goout
1          no      yes     yes        no        no       4         3      4
2          no       no     yes       yes        no       5         3      3
3          no      yes     yes       yes        no       4         3      2
4         yes      yes     yes       yes       yes       3         2      2

   Dalc  Walc  health  absences  G1  G2  G3
0  Dalc  Walc  health  absences  G1  G2  G3
1     1     1       3         6   5   6   6
2     1     1       3         4   5   5   6
3     2     3       3        10   7   8  10
4     1     1       5         2  15  14  15

In [50]:
print(data.head())

   school  sex  age  address  famsize  Pstatus  Medu  Fedu     Mjob      Fjob  \
0  school  sex  age  address  famsize  Pstatus  Medu  Fedu     Mjob      Fjob
1      GP    F   18        U      GT3        A     4     4  at_home   teacher
2      GP    F   17        U      GT3        T     1     1  at_home     other
3      GP    F   15        U      LE3        T     1     1  at_home     other
4      GP    F   15        U      GT3        T     4     2   health  services

   reason  guardian  traveltime  studytime  failures  schoolsup  famsup  paid  \
0  reason  guardian  traveltime  studytime  failures  schoolsup  famsup  paid
1  course    mother           2          2         0        yes      no    no
2  course    father           1          2         0         no     yes    no
3   other    mother           1          2         3        yes      no   yes
4    home    mother           1          3         0         no     yes   yes

   activities  nursery  higher  internet  romantic  famrel  freetime  goout  \
0  activities  nursery  higher  internet  romantic  famrel  freetime  goout
1          no      yes     yes        no        no       4         3      4
2          no       no     yes       yes        no       5         3      3
3          no      yes     yes       yes        no       4         3      2
4         yes      yes     yes       yes       yes       3         2      2

   Dalc  Walc  health  absences  G1  G2  G3
0  Dalc  Walc  health  absences  G1  G2  G3
1     1     1       3         6   5   6   6
2     1     1       3         4   5   5   6
3     2     3       3        10   7   8  10
4     1     1       5         2  15  14  15